name: Build and Publish Frontend

on:
  workflow_dispatch:
  pull_request:
    types: ["closed"]
    branches: [ "main", "devops/**"]

jobs:
  - name: deploy
    uses: ".github/templates"
    with:
      buildpath: "frontend"
