name: Build and Publish Frontend

on:
  workflow_dispatch:
  pull_request:
    types: ["closed"]
    branches: [ "main", "devops/**"]

env:
  REGISTRY: ghcr.io/hft-projektteam
  IMAGE_NAME: friendify_frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag image
        run: |
          IMAGE_TAG=latest

          if [ "${{ github.event_name }}" == "pull_request" ]; then
            IMAGE_TAG=pr-${{ github.event.number }}
          else
            IMAGE_TAG=$(git rev-parse --short HEAD)
          fi

          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}