name: Build and Publish Backend

on:
  workflow_dispatch:
  pull_request:
    types: ["closed"]
    branches: [ "main", "devops/**"]

env:
  REGISTRY: ghcr.io/hft-projektteam
  IMAGE_NAME: friendify_frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Build and push using template
        uses: ./.github/workflows/templates/deploy-template.yml
        with:
          buildpath: ./frontend
