name: Deploy Docker Compose to Portainer

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and tag Docker image - backend", "Build and tag Docker image - frontend"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn          

      - name: Setup VPN config
        run: |
          echo "${{ secrets.CA_CRT }}" > ca.crt
          echo "${{ secrets.USER_CRT }}" > user.crt
          echo "${{ secrets.USER_KEY }}" > user.key
          echo "${{ secrets.SECRET_USERNAME_PASSWORD }}" > secret.txt
          echo "${{ secrets.TLS_KEY }}" > tls.key
          echo "${{ secrets.TLS_KEY }}" > GitHub_nopass.ovpn

      - name: Connect VPN
        run: sudo openvpn ./GitHub_nopass.ovpn &
        # run: sudo openvpn --config ".github/vpn/client.ovpn" --log "vpn.log" --daemon

      - name: Wait for a VPN connection
        timeout-minutes: 1
        run: until ping -c1 10.10.10.1; do sleep 2; done

      - name: Deploy
        run: |
          curl -H "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}" 10.10.10.1:4231/v1/update

      - name: Kill VPN connection
        if: always()
        run: |
          sudo chmod 777 vpn.log
          sudo killall openvpn

      - name: Upload VPN logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: VPN logs
          path: vpn.log