name: Test Frontend

on:
  workflow_dispatch:
  pull_request:
    types: ['opened', 'reopened', 'edited']
    branches: ['main', 'devops/**']
    paths:
      - 'frontend/**'

env:
  BADGE_BRANCH: frontend/badges

jobs:
  test-frontend:
    name: Check frontend source code
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [18.x]
        #See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} with yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Prettier Check
        run: yarn format:check
      - name: Lint
        run: yarn lint
      - name: Yarn test
        run: yarn test

      - name: check build envoriment
        run: |
          ls -alh .
          pwd

      - name: Delete remote badges branch
        run: git push origin --delete $BADGE_BRANCH

      - name: Create badges branch
        run: git checkout -b $BADGE_BRANCH

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: '*'
          coverage-summary-path: /home/runner/work/ip2/ip2/frontend/coverage/coverage-summary.json
          target-branch: frontend/badges

      - name: Push badges branch
        run: git push origin $BADGE_BRANCH

