name: Test Backend

on:
  workflow_dispatch:
  pull_request:
    types: ['opened', 'reopened', 'edited']
    branches: ['main', 'devops/**']
    paths:
      - 'backend/**'

env:
  BADGE_BRANCH: backend/badges

jobs:
  test-backend:
    name: Check backend source code
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        node-version: [18.x]
        #See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: e2e_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} with yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: backend/yarn.lock
      - name: Yarn install
        run: yarn install --frozen-lockfile
      #      - name: Prettier Check
      #       run: yarn format:check
      - name: Lint
        run: yarn lint
      - name: Yarn test
        run: yarn test:ci_cd --coverage

      - name: Delete remote badges branch
        run: git push origin --delete $BADGE_BRANCH

      - name: Create badges branch
        run: git checkout -b $BADGE_BRANCH

      - name: Generating coverage badges
        uses: jpb06/jest-badge-action@latest
        with:
          branches: '*'
          coverage-summary-path: /home/runner/work/ip2/ip2/backend/coverage/coverage-summary.json
          target-branch: $BADGE_BRANCH

      - name: Push badges branch
        run: git push origin $BADGE_BRANCH