name: Test

on:
  workflow_dispatch:
  pull_request:
    types: ['opened', 'reopened', 'edited']
    branches: ['main', 'devops/**']

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'backend'
  test-frontend:
    name: Check frontend source code
    runs-on: ubuntu-latest
    needs: paths-filter
    if: needs.paths-filter.outputs.frontend == 'true'

    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [18.x]
        #See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} with yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Prettier Check
        run: yarn format:check
      - name: Lint
        run: yarn lint
      - name: Yarn test
        run: yarn test
        
  test-backend:
    name: Check backend source code
    runs-on: ubuntu-latest
    needs: paths-filter
    if: needs.paths-filter.outputs.backend == 'true'

    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        node-version: [18.x]
        #See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} with yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: backend/yarn.lock
      - name: Yarn install
        run: yarn install --frozen-lockfile
#      - name: Prettier Check
#       run: yarn format:check
      - name: Lint
        run: yarn lint
      - name: Yarn test
        run: yarn test
