name: deploy

inputs:
  buildpath:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag image
      run: |
        IMAGE_TAG=latest
  
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          IMAGE_TAG=pr-${{ github.event.number }}
        else
          IMAGE_TAG=$(git rev-parse --short HEAD)
        fi
  
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.buildpath }}
        push: true
        tags: |
          ghcr.io/hft-projektteam/friendify_${{ inputs.buildpath }}:latest
          ghcr.io/hft-projektteam/friendify_${{ inputs.buildpath }}:${{ env.IMAGE_TAG }}
